print("============================ ")
print("~~~~~~~~~My Profile~~~~~~~~|")
print("============================ ")
print("Name       : Mairaj Khan    |")
print("Age        : 18             |")
print("Address    : Sakinaka       |")
print("Class 10th : 82.2%          |")
print("Class 12th : 60.33%         |")
print("Number     : 9068560386     |")
print("============================")
print("*********THANK YOU**********")
print("============================")
